# Generated by Django 3.2.4 on 2021-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d11', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docfield',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='docfieldvalue',
            unique_together={('doc', 'field')},
        ),
        migrations.AlterIndexTogether(
            name='docfieldvalue',
            index_together=set(),
        ),
    ]
