# Generated by Django 3.2.4 on 2021-08-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('d11', '0002_auto_20210818_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='aleph_abstract_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='aleph_abstract_id_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='aleph_dissertation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='aleph_dissertation_id_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='type',
            field=models.CharField(
                choices=[('str', 'Строка'), ('int', 'Целое число'), ('float', 'Число'), ('date', 'Дата'),
                         ('datetime', 'Дата и время')], default='str', max_length=50),
        ),

        migrations.RenameField(
            model_name='doc',
            old_name='aleph_abstract_id',
            new_name='aleph_synopsis_id',
        ),
        migrations.RemoveField(
            model_name='doc',
            name='aleph_abstract_id_date',
        ),
        migrations.AddField(
            model_name='doc',
            name='aleph_synopsis_id_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='aleph_dissertation_id_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
