# Generated by Django 3.2.9 on 2021-11-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d11', '0005_docalephcard_files_export'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ['created_at']},
        ),
    ]
