# Generated by Django 3.2.9 on 2021-11-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d11', '0006_alter_doc_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttoaleph',
            name='docs',
            field=models.ManyToManyField(related_name='exports_to_aleph', to='d11.Doc'),
        ),
        migrations.AlterField(
            model_name='importfromaleph',
            name='docs',
            field=models.ManyToManyField(related_name='imports_from_aleph', to='d11.Doc'),
        ),
    ]
