# Generated by Django 3.2.9 on 2021-11-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d11', '0007_auto_20211111_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
