# Generated by Django 3.2.12 on 2022-02-09 18:10

import d11.models.aleph
import d11.models.doc
import d11.models.doc_aleph
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d11', '0010_alter_exporttoaleph_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectorimport',
            options={'ordering': ['-created_at'], 'verbose_name': 'импорт из источника', 'verbose_name_plural': 'импорт из источников'},
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'ordering': ['created_at'], 'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterModelOptions(
            name='docalephcard',
            options={'verbose_name': 'карточка Алеф', 'verbose_name_plural': 'карточки Алеф'},
        ),
        migrations.AlterModelOptions(
            name='docalephcardfilesexport',
            options={'verbose_name': 'экспорт файлов карточек Алеф', 'verbose_name_plural': 'экспорты файлов карточек Алеф'},
        ),
        migrations.AlterModelOptions(
            name='docfield',
            options={'verbose_name': 'поле записей', 'verbose_name_plural': 'поля записей'},
        ),
        migrations.AlterModelOptions(
            name='docfieldvalue',
            options={'ordering': ['-id'], 'verbose_name': 'значение поля записи', 'verbose_name_plural': 'значения полей записи'},
        ),
        migrations.AlterModelOptions(
            name='exporttoaleph',
            options={'verbose_name': 'экспорт записей в Алеф', 'verbose_name_plural': 'экспорты записей в Алеф'},
        ),
        migrations.AlterModelOptions(
            name='importfromaleph',
            options={'verbose_name': 'импорт записей из Алеф', 'verbose_name_plural': 'импорты записей из Алеф'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['id'], 'verbose_name': 'источник', 'verbose_name_plural': 'источники'},
        ),
        migrations.AlterField(
            model_name='collectorimport',
            name='collector_name',
            field=models.CharField(max_length=1000, verbose_name='тип импорта'),
        ),
        migrations.AlterField(
            model_name='collectorimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='collectorimport',
            name='docs',
            field=models.ManyToManyField(related_name='_d11_collectorimport_docs_+', to='d11.Doc', verbose_name='записи'),
        ),
        migrations.AlterField(
            model_name='collectorimport',
            name='extra',
            field=models.JSONField(default=dict, verbose_name='доп. данные'),
        ),
        migrations.AlterField(
            model_name='collectorimport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to=d11.models.doc.doc_upload_to, verbose_name='файл карточки на сайте источнике'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='content_file_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='md5 файла карточки на сайте источнике'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='is_autoref_exist',
            field=models.BooleanField(default=False, verbose_name='наличие автореферата'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='is_ready_for_abis',
            field=models.BooleanField(default=False, verbose_name='готовность к синхронизации с Алеф'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='is_sync_abis',
            field=models.BooleanField(default=True, verbose_name='отслеживать изменения в Алеф'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='is_track_external',
            field=models.BooleanField(default=True, verbose_name='отслеживать изменения на сайте источнике'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='d11.source', verbose_name='источник'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='url',
            field=models.URLField(max_length=1000, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='docalephcard',
            name='aleph_fields_json',
            field=models.JSONField(default=dict, verbose_name='доп. данные'),
        ),
        migrations.AlterField(
            model_name='docalephcard',
            name='aleph_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Алеф ID'),
        ),
        migrations.AlterField(
            model_name='docalephcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='docalephcard',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aleph_cards', to='d11.doc', verbose_name='запись'),
        ),
        migrations.AlterField(
            model_name='docalephcard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=d11.models.doc_aleph.doc_aleph_card_upload_to, verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='docalephcard',
            name='kind',
            field=models.CharField(choices=[('synopsis', 'Synopsis'), ('dissertation', 'Dissertation')], max_length=50, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='docalephcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='docalephcardfilesexport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='docalephcardfilesexport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='is_auto',
            field=models.BooleanField(default=True, verbose_name='создано автоматически'),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='label',
            field=models.CharField(max_length=1000, unique=True, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='label_aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None, verbose_name='синонимы'),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='docfield',
            name='type',
            field=models.CharField(choices=[('str', 'Строка'), ('int', 'Целое число'), ('float', 'Число'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('file', 'Файл')], default='str', max_length=50, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='docfieldvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='docfieldvalue',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_values', to='d11.doc', verbose_name='запись'),
        ),
        migrations.AlterField(
            model_name='docfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_values', to='d11.docfield', verbose_name='поле'),
        ),
        migrations.AlterField(
            model_name='docfieldvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='docfieldvalue',
            name='value',
            field=models.JSONField(verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='exporttoaleph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='exporttoaleph',
            name='docs',
            field=models.ManyToManyField(related_name='exports_to_aleph', to='d11.Doc', verbose_name='записи'),
        ),
        migrations.AlterField(
            model_name='exporttoaleph',
            name='docs_serialized_file',
            field=models.FileField(blank=True, help_text='формат Aleph SEQ', null=True, upload_to=d11.models.aleph.import_export_upload_to_serialized_file, verbose_name='файл c записями для загрузки в Aleph'),
        ),
        migrations.AlterField(
            model_name='exporttoaleph',
            name='extra',
            field=models.JSONField(default=dict, help_text='доп. данные'),
        ),
        migrations.AlterField(
            model_name='exporttoaleph',
            name='kind',
            field=models.CharField(choices=[('create_with_autoref', 'Create With Autoref'), ('create_without_autoref', 'Create Without Autoref'), ('update_with_autoref', 'Update With Autoref'), ('update_without_autoref', 'Update Without Autoref')], max_length=50, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='exporttoaleph',
            name='result_file',
            field=models.FileField(blank=True, help_text='формат Aleph SEQ', null=True, upload_to=d11.models.aleph.import_export_upload_to_result_file, verbose_name='файл c результатами из Aleph'),
        ),
        migrations.AlterField(
            model_name='exporttoaleph',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='importfromaleph',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='importfromaleph',
            name='docs',
            field=models.ManyToManyField(related_name='imports_from_aleph', to='d11.Doc', verbose_name='записи'),
        ),
        migrations.AlterField(
            model_name='importfromaleph',
            name='docs_serialized_file',
            field=models.FileField(blank=True, help_text='формат Aleph SEQ', null=True, upload_to=d11.models.aleph.import_export_upload_to_serialized_file, verbose_name='файл c записями для загрузки в Aleph'),
        ),
        migrations.AlterField(
            model_name='importfromaleph',
            name='extra',
            field=models.JSONField(default=dict, help_text='доп. данные'),
        ),
        migrations.AlterField(
            model_name='importfromaleph',
            name='result_file',
            field=models.FileField(blank=True, help_text='формат Aleph SEQ', null=True, upload_to=d11.models.aleph.import_export_upload_to_result_file, verbose_name='файл c результатами из Aleph'),
        ),
        migrations.AlterField(
            model_name='importfromaleph',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='source',
            name='attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='доп. данные'),
        ),
        migrations.AlterField(
            model_name='source',
            name='collector_class',
            field=models.CharField(choices=[['CollectorVakAdvert', 'ВАК :: ОБЪЯВЛЕНИЯ О ЗАЩИТАХ ВАК'], ['CollectorVakIndependent', 'ВАК :: САМОСТОЯТЕЛЬНОЕ ПРИСУЖДЕНИЕ СТЕПЕНЕЙ']], max_length=100, verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='включен'),
        ),
        migrations.AlterField(
            model_name='source',
            name='label',
            field=models.CharField(max_length=1000, unique=True, verbose_name='название'),
        ),
    ]
