version: '3.8'

services:
  d11-nginx:
    image: d11/nginx
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: nginx
    restart: always
    volumes:
      - ../../www/storage:/www/storage
#      - ../docker/nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 10031:80
      - 10032:81
    networks:
      - d11

  d11-app-api: &d11-app-api
    image: d11/app
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: app
    restart: always
    depends_on:
      - d11-pg
      - d11-redis
    volumes:
      - ../../www/storage:/www/storage
      - ../:/app
    command: './docker/entry-point/entry-point.sh django'
    networks:
      - d11

  d11-app-celery:
    <<: *d11-app-api
    depends_on:
      - d11-app-api
    ports: [ ]
    command: './docker/entry-point/entry-point.sh django-celery'

  d11-app-celery-beat:
    <<: *d11-app-api
    depends_on:
      - d11-app-api
    ports: [ ]
    command: './docker/entry-point/entry-point.sh django-celery-beat'

  d11-pg:
    image: postgres:13.3
    restart: always
    user: postgres
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=d11
      - POSTGRES_PASSWORD=not1pass
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGUSER=postgres
    volumes:
      - ../../www/.docker-data/postgres:/var/lib/postgresql/data
    ports:
      - 10020:5432
    networks:
      - d11

  d11-redis:
    image: redis:6.2.4-alpine
    restart: always
    volumes:
      - ../../www/.docker-data/redis:/data/
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - d11

  d11-app-flower:
    image: mher/flower
    restart: always
    depends_on:
      - d11-app-celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/5
      - FLOWER_PORT=5555
      - FLOWER_ADDRESS=0.0.0.0
      - FLOWER_BASIC_AUTH=d11-flower:not1pass
    networks:
      - d11


networks:
  d11:
    ipam:
      driver: default

