# Generated by Django 3.2.9 on 2021-11-16 09:20

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('d11', '0008_source_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None)),
                ('excel_report', models.FileField(blank=True, null=True, upload_to=main.models.email_notification_upload_to)),
                ('docs', models.ManyToManyField(blank=True, related_name='emails_notifications', to='d11.Doc')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
